---
- name: Setup docker-engine yum repository
  yum_repository:
    name: dockerrepo
    description: Docker Repository
    baseurl: https://yum.dockerproject.org/repo/main/centos/$releasever/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://yum.dockerproject.org/gpg

- name: Install docker packages
  package:
    name: docker-engine
    state: present

- name: Enable/Start docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Configure daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
  notify: restart docker

- name: Install docker-compose
  pip:
    name:
      - pip
      - docker-compose
      - docker-py
    state: latest
